### ISSUE TITLE
Docker not works

### ISSUE THREAD

**Issue by Ahnhojin1223** [CPS-TUWien/racing_dreamer#12]
I want to install docker environment at Ubuntu 20.04 and train Model Free baselines to compare with dreamer.
But when I make docker image, error occured.
Can you check it????

And is it okay to train multiple baselines using docker??

**Comment by axelbr** [comment]
Please provide the exact command you used for building the images and the error message. 

> And is it okay to train multiple baselines using docker??

What do you mean with that?

**Comment by Ahnhojin1223** [comment]
Oh I missed to upload error message!!!

My env is Ubuntu 20.04 and 22.04

I clone your repo and build docker image using command ./scripts/build_all.sh

When build Docker.acme
![image](https://github.com/user-attachments/assets/314f81b9-9141-4b68-83d0-9f9324439bc1)

When build Docker.sb2
![image](https://github.com/user-attachments/assets/875dd057-a0ff-49a9-be63-6e08dc22b55a)

When build Docker.sb3
![image](https://github.com/user-attachments/assets/1ab25c83-4aa6-4e63-94ed-927bdef7f420)

When I change Docker file to solve these errors, but I can't solve it.

```
And is it okay to train multiple baselines using docker??
```
It means...
Using ./scripts/start_ids.sh 1 2 3 4 13, I know that baslines related to the austria map are learned, and I wonder if they can be learned in parallel with one GPU.

**Comment by axelbr** [comment]
Ok, it looks like the repositories/packages are outdated or not supported anymore. This project started in 2020 and some software packages reached EOL already.
Unfortunately, we do not have enough capacity to fix this anytime soon. However, we are happy to accept PR's if you manage to fix those dependency issues.

**Comment by Ahnhojin1223** [comment]
Okay, I'll contact you if it's resolved.
Is each requirement.txt in the baselines/docker the condition for learning the baseline???

**Comment by axelbr** [comment]
Those are the python dependencies (obtained via `pip freeze`) for the different frameworks.
