### ISSUE TITLE
ModuleNotFoundError: No module named 'baselines'

### ISSUE THREAD

**Issue by Vishal1711** [CPS-TUWien/racing_dreamer#5]
I try to run file `run_experiments.py` from baselines. I faced run-time exceptions as below which is related to the module not being found. I tried **Remedies**
[Stackoverflow Link](https://stackoverflow.com/questions/54598292/python-modulenotfounderror-when-trying-to-import-module-from-imported-package/54613085)

1. Added path of baseline directory at $PYTHONPATH variable however it didn't work.

```
df@u20:~/2D_Racing/racing_dreamer/baselines$ pwd
/home/df/2D_Racing/racing_dreamer/baselines
df@u20:~/2D_Racing/racing_dreamer/baselines$ PYTHONPATH=$PYTHONPATH:/home/df/2D_Racing/racing_dreamer/baselines
df@u20:~/2D_Racing/racing_dreamer/baselines$ export PYTHONPATH
df@u20:~/2D_Racing/racing_dreamer/baselines$ echo $PYTHONPATH
/opt/ros/noetic/lib/python3/dist-packages:/home/df/2D_Racing/racing_dreamer/baselines
```
2. Added `__init__.py` file in baselines.

```
df@u20:~/2D_Racing/racing_dreamer/baselines$ touch __init__.py
df@u20:~/2D_Racing/racing_dreamer/baselines$ ls
docker  experiments.csv  hyperparams  __init__.py  logs  racing  README.md  requirements.txt  run_experiments.py  run_tuning.py  scenarios  scripts  src

```

**Error -**
```
df@u20:~/2D_Racing/racing_dreamer/baselines$ python3 run_experiments.py
74769887
Traceback (most recent call last):
  File "run_experiments.py", line 41, in <module>
    main(args)
  File "run_experiments.py", line 22, in main
    experiment, agent_ctor = dispatch_experiment(args, logdir)
  File "/home/df/2D_Racing/racing_dreamer/baselines/racing/experiments/__init__.py", line 7, in dispatch_experiment
    from baselines.racing.experiments.sb3 import make_experiment
ModuleNotFoundError: No module named 'baselines'
```

**Comment by axelbr** [comment]
Ok, I fixed some imports. It seems like the transfer to the public repo messed up some module structure. I would recommend you to create a virtualenvironment (python -m venv venv) inside the baselines directory. Then source it and install the requirements. This should work:
```
cd baselines
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python run_experiments.py --agent ...
```

**Comment by axelbr** [comment]
In general, I would recommend docker, as it provides the same environment regardless of your individual setup.

**Comment by Vishal1711** [comment]
Thank you @axelbr for the above recommendation. I created virtualenv inside the baseline directory and installed the requirements. When I run file `run_experiments.py` on my ubuntu system, it shows me an error like this.

1. Error on ubuntu system after running `run_experiments.py`.

```
vjadhav) df@u20:~/2D_Racing/racing_dreamer/baselines$ python run_experiments.py 
12556080
pybullet build time: Dec  1 2021 18:33:43
Logging directory:  logs/experiments/austria_sac_max_progress_12556080_1638686930.0395713
Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
/home/df/2D_Racing/racing_dreamer/baselines/vjadhav/lib/python3.8/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "run_experiments.py", line 41, in <module>
    main(args)
  File "run_experiments.py", line 23, in main
    experiment.run(steps=args.steps, agent_ctor=agent_ctor, eval_every_steps=args.eval_interval)
  File "/home/df/2D_Racing/racing_dreamer/baselines/racing/experiments/sb3/sb_experiment.py", line 110, in run
    model = self.configure_agent(agent_ctor)
  File "/home/df/2D_Racing/racing_dreamer/baselines/racing/experiments/sb3/sb_experiment.py", line 115, in configure_agent
    return agent_ctor(env=self.train_env, seed=self._seed, tensorboard_log=f'{self._logdir}')
  File "/home/df/2D_Racing/racing_dreamer/baselines/vjadhav/lib/python3.8/site-packages/stable_baselines3/sac/sac.py", line 143, in __init__
    self._setup_model()
  File "/home/df/2D_Racing/racing_dreamer/baselines/vjadhav/lib/python3.8/site-packages/stable_baselines3/sac/sac.py", line 169, in _setup_model
    self.log_ent_coef = th.log(th.ones(1, device=self.device) * init_value).requires_grad_(True)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
Process Process-1:
Process Process-2:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/df/2D_Racing/racing_dreamer/baselines/vjadhav/src/racecar-gym/racecar_gym/envs/util/subprocess_env.py", line 22, in _start
    command, kwargs = connection.recv()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/df/2D_Racing/racing_dreamer/baselines/vjadhav/src/racecar-gym/racecar_gym/envs/util/subprocess_env.py", line 22, in _start
    command, kwargs = connection.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

2. In another attempt, I tried to run the file on the high-performance computing platform. By using multiple GPUs, I want to reduce the training time. I got errors like below. 

```
(venv) [vjadhav@node0131 baselines]$ python run_experiments.py
12150517
pybullet build time: Dec  1 2021 18:32:25
Logging directory:  logs/experiments/austria_sac_max_progress_12150517_1638687376.5793884
Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
start learning
2021-12-05 01:56:31.223732: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-12-05 01:56:31.223765: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Logging to logs/experiments/austria_sac_max_progress_12150517_1638687376.5793884/SAC_1
```
And when I run requirements.txt on HPC it was showing error when installing tfp-nightly.

```
INFO: pip is looking at multiple versions of tfp-nightly to determine which version is compatible with other requirements. This could take a while.
Collecting tfp-nightly
  Using cached tfp_nightly-0.16.0.dev20211203-py2.py3-none-any.whl (5.8 MB)
```

**Comment by axelbr** [comment]
Ad 1: This looks like you do not have the correct pytorch version installed for your GPU. It says: `RuntimeError: CUDA error: no kernel image is available for execution on the device`. Unfortunately, this is outside of my control.
Ad 2: There is no error. Its just not recognizing your CUDA installation, but it seems to work on CPU. Please check your CUDA installation in order to run it on a GPU.
Ad 3: This is also no error, just an info.

To verify that it works, you could try to run the Docker containers on your cluster. The images provide all the dependencies like CUDA and tensorflow and (with some luck) work out of the box. I also fixed the docker image versions to the ones we used when we did the experiments. Run `./scripts/build_all.sh` to build the images. Then run an experiment. Details can be found in the README.

**Comment by Vishal1711** [comment]
I have tried and tested the project with docker previously and it went very well. But I want to run this on a high-performance computing cluster for performance. I have access to the cluster there I do not have access to build a docker image on the cluster due to obvious reasons. So help me with correct versions of dependencies and python. In `requirements.txt` the exact version of dependencies is not mentioned therefore pip tries to resolve with various versions however it seems the issue with version conflict. 
Example: 
It shows error of numpy-
`jmp 0.0.2 requires numpy>=1.19.5, but you have numpy 1.18.5 which is incompatible.`
When I upgrade numpy -
`tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you may have numpy 1.19.5 which is incompatible.`

 Can I get the exact version of dependencies including the python version? So, that I can exactly mimic the environment in HPC.

**Comment by axelbr** [comment]
Ok. I reported the exact pip versions for [ACME](https://github.com/CPS-TUWien/racing_dreamer/blob/5bf12504711551993be409b1e69c299746bdd3fa/baselines/docker/requirements_acme.txt), [SB3](https://github.com/CPS-TUWien/racing_dreamer/blob/5bf12504711551993be409b1e69c299746bdd3fa/baselines/docker/requirements_sb3.txt) and [SB2](https://github.com/CPS-TUWien/racing_dreamer/blob/5bf12504711551993be409b1e69c299746bdd3fa/baselines/docker/requirements_sb2.txt) directly from within the containers. 

Please note that this still does not guarantee that it runs on your cluster, because there you probably have some other OS version than we have. For exact details regarding the system-level dependencies please consult the specific Dockerfile base images on Dockerhub.
