### ISSUE TITLE
How to obtain the F1tenth-like tracks simulation demo?

### ISSUE THREAD

**Issue by Zhimin-C** [CPS-TUWien/racing_dreamer#8]
Thanks for the great work!. Now I am trying to reproduce the simulation result and have trained the model. However, I cannot find how to obtain the F1tenth-like tracks simulation demo shown at the beginning. May you share the code to generate such a good demo. Thanks!

Zhimin Chen

**Comment by axelbr** [comment]
To create a video of an agent, you can use the render function of the environment and then stack the frames. See at our example in the [racecar_gym](https://github.com/axelbr/racecar_gym/blob/master/examples/simple_usage.py) to get an idea. To create a video from the frames, you can use this [script](https://github.com/CPS-TUWien/racing_dreamer/blob/5bf12504711551993be409b1e69c299746bdd3fa/baselines/racing/__init__.py).
