### ISSUE TITLE
Resource not found: f1tenth_demo

### ISSUE THREAD

**Issue by zzjun725** [CPS-TUWien/racing_dreamer#9]
Hello! 
Thanks for the amazing work.

When I try to run the launch file(roslaunch f1tenth_dreamer simulator.launch), an error occurs: 
Resource not found: f1tenth_demo 

I can not find this pkg in your code, so I wonder how I can solve this issue?

Thank you very much !

**Comment by zzjun725** [comment]
Besides, when I tried to run the training code, I got: 

ModuleNotFoundError: No module named 'agents'

and the related line is 
from agents.gap_follower import GapFollower

I search the code and yet I can not find a class named GapFollower. Is there a dependent issue?

**Comment by axelbr** [comment]
Hello, thank you for reaching out.
@oddest-prime Can you have a look at this?

**Comment by zmm525** [comment]
Hi zzjun,

I also encountered this problem about 'from agents.gap_follower import GapFollower'.
Have you solved it now?

Thanks!

**Comment by axelbr** [comment]
Hi, thanks for using our code. sorry for the delay, we were quite busy last week. we will work on it this week.

**Comment by oddest-prime** [comment]
the problem that f1tenth_demo was not found should now be resolved in https://github.com/CPS-TUWien/racing_dreamer/commit/7bb552d7cef04017c7b3e791697e6e7aa662bda8

**Comment by zzjun725** [comment]
> the problem that f1tenth_demo was not found should now be resolved in [7bb552d](https://github.com/CPS-TUWien/racing_dreamer/commit/7bb552d7cef04017c7b3e791697e6e7aa662bda8)

Thank you very much! I pulled the latest commit. But I still can not find agents.gap_follower, could you also help with that?

**Comment by zzjun725** [comment]
> Hi zzjun,
> 
> I also encountered this problem about 'from agents.gap_follower import GapFollower'. Have you solved it now?
> 
> Thanks!

For reference, if you just want to run this repo, you can reset both the commits of the environment(racecar_gym) and this repo itself to the version around 2021.5. I tried and it works. I think the missing of some dependency is just because of the difference between the latest commit and the former ones.

**Comment by zmm525** [comment]
> > Hi zzjun,
> > I also encountered this problem about 'from agents.gap_follower import GapFollower'. Have you solved it now?
> > Thanks!
> 
> For reference, if you just want to run this repo, you can reset both the commits of the environment(racecar_gym) and this repo itself to the version around 2021.5. I tried and it works. I think the missing of some dependency is just because of the difference between the latest commit and the former ones.

I have solved this problem using the method you provided.
Thank you very much!

**Comment by axelbr** [comment]
@zzjun725 @zmm525 
Sorry for the misunderstanding. I thought this was resolved already by @oddest-prime and that it was a ROS-related issue. It turns out that this was a dependency from racecar_gym (see #11).
